#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

(
    echo "# This file is generated by scripts/cmake-update-source-files.sh"
    echo "set(SourceFiles"
    find "$PROJECT_ROOT/src" -type f \( -name "*.h" -o -name "*.hpp" -o -name "*.c" -o -name "*.cpp" \) | \
        sed "s|${PROJECT_ROOT}/||" | \
        sed 's/^/    /'
    echo ")"
) > "$PROJECT_ROOT/SourceFiles.cmake"
